// Generated by https://quicktype.io

import { Person } from "./person.model";

export interface PeopleResponse {
    count:    number;
    next:     string;
    previous: null;
    results:  Person[];
}


